---
- name: Install pip3
  become: true
  when: ansible_os_family == "Debian"
  apt:
      name: python3-pip
      update_cache: true
      state: latest

- name: Install pipenv
  become: true
  pip:
      name: pipenv
      executable: pip3
