---
- name: install pyethereum apt dependencies
  apt: name={{ item }}
  become: yes
  with_items:
      - libssl-dev 
      - build-essential 
      - automake 
      - pkg-config 
      - libtool 
      - libffi-dev 
      - libgmp-dev 
      - libyaml-cpp-dev

- name: install pipenv dependencies
  command: pipenv install --python 3.6
  args:
      chdir: sanity/
